# [master]
# raspi-103.local
# raspi-104.local


# [node]
# raspi-100
# raspi-101
# raspi-102

# only required if proxmox_lxc_configure: true
# must contain all proxmox instances that have a master or worker node
# [proxmox]
# 192.168.30.43



master:
  hosts:
    raspi-104.local: # 192.168.1.127: 
    raspi-103.local: # 192.168.1.137: 

node:
  hosts:
    raspi-100.local: # 192.168.1.236: 
    # raspi-101.local: # 192.168.1.103: 
    raspi-102.local: # 192.168.1.209: 



k3s_cluster:
  children:
    master:
    node: